from enum import Enum

PACKET_RESET_SYMBOL = 'r'
SIZE_OF_BYTE = 2
MAX_PACKET_DIGIT = '9' # change it to high packet digit
MAX_BYTE_SIZE = int(MAX_PACKET_DIGIT*SIZE_OF_BYTE)
MAX_PACKET_DIGITS_SIZE = 9
CLOSE_PACKET_MARK = '99'

class PktType(Enum):
    DATA = 1
    ACK =  2
    FIN =  3

class PktSide(Enum):
    VICTIM =   0
    ATTACKER = 1

#Fields size in bits
TYPE_SIZE= 1
LEN_SIZE = 2
SEQ_SIZE = 1
CHECKSUM_SIZE = 2
SIDE_SIZE = 1

DATA_PACKET_SIZE= len(PACKET_RESET_SYMBOL)+TYPE_SIZE+LEN_SIZE+SEQ_SIZE+CHECKSUM_SIZE
ACK_PACKET_SIZE = len(PACKET_RESET_SYMBOL)+TYPE_SIZE+SEQ_SIZE+CHECKSUM_SIZE
FIN_PACKET_SIZE = len(PACKET_RESET_SYMBOL)+TYPE_SIZE+CHECKSUM_SIZE+SIDE_SIZE